name: stripes_sandbox_aws
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripes_ui:
    git:
      url: https://github.com/dylanb7/stripes_ui
      branch: master
  stripes_backend_helper:
    git:
      url: https://github.com/dylanb7/stripes_backend_helper
      branch: master
  amplify_flutter: ^2.0.0
  amplify_api: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  url_strategy: ^0.2.0
  sqflite_common_ffi_web: ^0.4.2+3
  sqflite: ^2.3.3
  sqflite_sqlcipher: ^2.2.1
  flutter_secure_storage: ^9.1.1
  rxdart: ^0.27.7
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "lib/assets/StripesIcon512.png"
  image_path_ios: "lib/assets/StripesIcon1024.png"
  min_sdk_android: 21
  background_color_ios: "#ffffff"
  background_color_android: "#ffffff"
  web:
    generate: true
    image_path: "libassets/StripesIcon1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
